# This rule is not used by the project jumpstarter-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over operator.jumpstarter.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jumpstarter-operator
    app.kubernetes.io/managed-by: kustomize
  name: jumpstarter-admin-role
rules:
- apiGroups:
  - operator.jumpstarter.dev
  resources:
  - jumpstarters
  verbs:
  - '*'
- apiGroups:
  - operator.jumpstarter.dev
  resources:
  - jumpstarters/status
  verbs:
  - get
