image: quay.io/jumpstarter-dev/jumpstarter-controller

namespace: ""

grpc:
  tls:
    enabled: false
    secret: ""

  # enabling ingress route
  ingress:
    enabled: false
    class: ""

  # enabling openshift route
  route:
    enabled: false
  
  # NodePort service for grpc, useful for local development
  nodeport:
    enabled: false
    port: 30010

imagePullPolicy: IfNotPresent
