enabled: true

image: quay.io/jumpstarter-dev/jumpstarter-controller
imagePullPolicy: IfNotPresent

grpc:
  tls:
    mode: "passthrough"
    port: 443

config:
  grpc:
    keepalive:
      # Safety: potentially makes server vulnerable to DDoS
      # https://grpc.io/docs/guides/keepalive/#how-configuring-keepalive-affects-a-call
      minTime: 3s
      permitWithoutStream: true
  authentication:
    internal:
      prefix: "internal:"
    # To trust service account tokens, first execute:
    #   kubectl create clusterrolebinding oidc-reviewer \
    #     --clusterrole=system:service-account-issuer-discovery \
    #     --group=system:unauthenticated
    # Then uncomment:
    #
    # jwt:
    # - issuer:
    #     url: https://kubernetes.default.svc.cluster.local
    #     audiences:
    #       - https://kubernetes.default.svc.cluster.local
    #     audienceMatchPolicy: MatchAny
    #     certificateAuthority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    #   claimMappings:
    #     username:
    #       claim: "sub"
    #       prefix: "kubernetes:"
