apiVersion: jumpstarter.dev/v1alpha1
kind: Client
metadata:
  labels:
    app.kubernetes.io/name: jumpstarter-router
    app.kubernetes.io/managed-by: kustomize
  name: client-sample
spec:
  oidcIssuer: http://host.docker.internal:5556/dex
  oidcSubject: CiQ3M2JjYTBiOS05YmU2LTRlNzMtYThmYi0zNDdjMmFjMjMyNTUSBWxvY2Fs
