## @section Global parameters
## @descriptionStart This section contains parameters common to all the
## components in the deployment.
## @descriptionEnd
##
## @param global.namespace Namespace where the components will be deployed.
## @param global.metrics.enabled Enable metrics exporting and service
## @param global.timestamp Timestamp to be used to trigger a new deployment, i.e. if you want pods to be restarted and pickup ":latest"

global:
  baseDomain: jumpstarter.my.domain.com
  namespace: jumpstarter-lab
  metrics:
      enabled: false
  timestamp: "" # can be used to timestamp deployments and make them reload

## @param jumpstarter-controller.namespace Namespace where the controller will be deployed, defaults to global.namespace.
## @param jumpstarter-controller.grpc.tls.mode Setup the TLS mode for endpoints, either "passthrough" or "reencrypt".
## @param jumpstarter-controller.grpc.tls.port Port to use for the gRPC endpoints ingress or route, this can be useful for ingress routers on non-standard ports.
