---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - exporters
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - exporters/finalizers
  - leases/finalizers
  verbs:
  - update
- apiGroups:
  - jumpstarter.dev
  resources:
  - exporters/status
  - leases/status
  verbs:
  - get
  - patch
  - update
