{{ range $k, $v := .Values.grpc.routers }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-router-{{ $k }}
    app.kubernetes.io/name: jumpstarter-controller
  name: jumpstarter-router-grpc-{{ $k }}
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
spec:
  type: {{ include "router.service.type" (list $ $k $v) }}

  ports:
  - name: grpc
    port: 8083
    protocol: TCP
    targetPort: 8083
    appProtocol: h2c # HTTP/2 over cleartext for gRPC (fixes edge termination in ingress/router)
    {{ if $v.service }}
    {{ if $v.service.nodePort }}
    nodePort: {{ $v.service.nodePort }}
    {{ end }}
    {{ end }}
  selector:
    control-plane: controller-router-{{ $k }}
{{ end }}
