{{ range $k, $v := .Values.grpc.routers }}
{{ if $v.ingress }}
{{ if $v.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    {{ if eq $.Values.grpc.tls.mode "passthrough" }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{ end }}
  name: jumpstarter-router-ingress-{{ $k }}
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
spec:
  {{ if $v.ingress.class }}
  ingressClassName: {{ $v.ingress.class }}
  {{ end }}
  rules:
  - host: {{ include "router.hostname" (list $ $k $v) }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jumpstarter-router-grpc-{{ $k }}
            port:
              number: 8083
  tls:
  - hosts:
      - {{ include "router.hostname" (list $ $k $v) }}
    {{ if $.Values.grpc.tls.routerCertSecret }}
    secretName: {{ $.Values.grpc.tls.routerCertSecret }}
    {{ end }}
{{ end }}
{{ end }}
{{ end }}
