name: End-to-end tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'release-*'
jobs:
  e2e-tests:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: jumpstarter-dev/jumpstarter-e2e@router
        with:
          controller-ref: ${{ github.ref }}
          # use the matching branch on the jumpstarter repo
          jumpstarter-ref: ${{ github.event.pull_request.base.ref }}
  e2e-tests-28d6b1cc3b49ab9ae176918ab9709a2e2522c97e:
    runs-on: ubuntu-latest
    steps:
      - uses: jumpstarter-dev/jumpstarter-e2e@11a5ce6734be9f089ec3ea6ebf55284616f67fe8
        with:
          controller-ref: ${{ github.ref }}
          jumpstarter-ref: 28d6b1cc3b49ab9ae176918ab9709a2e2522c97e
